### ISSUE TITLE
device_update函数中get_time()函数疑似过于影响性能

### ISSUE THREAD

**Issue by Frankslu** [NJU-ProjectN/nemu#108]
nemu在关闭trace等其他无关选项后，运行microbench的分数如下

![bef88c39a5aae229e69a8a88915f6172](https://github.com/user-attachments/assets/9186f9d9-8bd4-450b-b22c-74587c6cb39e)

其中times表示的是device_update函数运行的次数。

若对device_update开头的部分改为如下形式：
```
void device_update() {
    static uint64_t cnt;
    if (cnt < 200000) {
        cnt++;
        return;
    }
    cnt = 0;
...
```
测得microbench分数如下：

![685afc6a556080d867706da47c259053](https://github.com/user-attachments/assets/68c79b76-24ba-42dc-baf3-3e555b62a16f)

进行修改后，nemu运行microbench的时间减少为原来的1/3，且device_update的频率比原来更高。因此，为了提高性能，是否可以去掉device_update开头的get_time函数，改用计数的方式调整device_update的频率？cnt具体的值可以进一步调整。

**Comment by sashimi-yzh** [comment]
你指出的这个现象是已知的，我手上有一版深度优化的代码，也是对这部分进行了改动，但可读性并不好。这个项目的首要目的是教学，有时候需要在教学考量和性能之间进行取舍，只要性能不是糟糕得无法忍受，还是会选择利于学生理解的实现方式，这样可以保证所有学生都能读懂代码。而对于想优化的学生，则可以作为一道思考题，让他们学会profiling并提出解决方案。

你提出的优化在大方向上是可行的，你可以继续思考一下如何自动调整`cnt`。不过出于上文的考虑，我们不打算主动“修复”这个问题。
