### ISSUE TITLE
LeakSanitizer fatal error

### ISSUE THREAD

**Issue by mo-vic** [NJU-ProjectN/nemu#110]
when run `make gdb` (with LeakSanitizer **ON**) and exiting nemu by typing `q`, the below LeakSanitizer pop up:

![dc2d384d42d70e09fe66133b10b4093c](https://github.com/user-attachments/assets/c691755b-4de1-4df8-9097-ef51d90282c3)

This existed in recent version of nemu, my another older version does not have this issue.

**Comment by sashimi-yzh** [comment]
The message says `HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)`. So do not use LeakSanitizer with gdb.

**Comment by mo-vic** [comment]
you are right, but the previous version, roughly 25/Aug/2024, does not show this message.

**Comment by sashimi-yzh** [comment]
Not showing this message does not mean that the behavior is defined to be right. It may be undefined behavior, but it did not crash in your previous run.
