### ISSUE TITLE
Maybe a  bug

### ISSUE THREAD

**Issue by SHE8081** [NJU-ProjectN/nemu#13]
ics2021/nemu/src/cup/cpu-exec.c  line 47：#define NUMBERIC_FMT MUXDEF(CONFIG_TARGET_AM, "%ld", "%'ld")  may be need to be changed as #define NUMBERIC_FMT MUXDEF(CONFIG_TARGET_AM, "%ld", "%lld")

**Comment by sashimi-yzh** [comment]
Can you explain more about your consideration?
