### ISSUE TITLE
fatal error: llvm/Support/TargetRegistry.h: No such file or directory

### ISSUE THREAD

**Issue by Tom-CaoZH** [NJU-ProjectN/nemu#16]
I have put forward a issues afternoon,but later i found that my ubuntu version is 20.04 and the requested is 21.04 . so i think the problem 
 is the version of llvm in my machine is too low . so i update it to llvm 14 -- the latest version .Howerver,i met another problem following
```+ CXX src/utils/disasm.cc
src/utils/disasm.cc:5:10: fatal error: llvm/Support/TargetRegistry.h: No such file or directory
    5 | #include "llvm/Support/TargetRegistry.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
i think the reason of this maybe i need to update other things ,but i reinstall all the things ,the error still exist.And i try to search for the answer but i haven't find it .And because i have used the ubuntu 20.04 for a long peroid of time ,so i haven't decide to change it to ubuntu 21.04.I hope you can give me some tips on how to solve this .Thank you.

**Comment by sashimi-yzh** [comment]
Try the followings:
1. install `llvm-11` in ubuntu 20.04
2. modify `nemu/src/utils/filelist.mk` to use `llvm-config-11` instead of `llvm-config`
3. compile again

**Comment by ZJsheep** [comment]
Don't seem to be the problem of Ubuntu version. I am also running 20.04 and have met no problems. Maybe `sudo apt update` and `sudo apt upgrade` will help?

**Comment by Tom-CaoZH** [comment]
> Try the followings:
> 
> 1. install `llvm-11` in ubuntu 20.04
> 2. modify `nemu/src/utils/filelist.mk` to use `llvm-config-11` instead of `llvm-config`
> 3. compile again

yes , thank you very much ,it works.

**Comment by Tom-CaoZH** [comment]
> Don't seem to be the problem of Ubuntu version. I am also running 20.04 and have met no problems. Maybe `sudo apt update` and `sudo apt upgrade` will help?

my origional version of llvm is 10 , maybe it is too low , i am a green hand ,i do not know much about it . Thank you for tips

**Comment by darkduckgo** [comment]
@sashimi-yzh thanks god.... follow the steps from your advices, I got the LD error (I search the error msg but failed)
my building env is **ubuntu16.04** (maybe I should use docker to install ubuntu21?), and I solved a lot of env problems before which are differ from ubuntu21

firstly, I download the binary package from llvm, and save it to `/usr/local/llvm`, add $PATH for `llvm/bin`, then I modify the `/etc/ld.so.conf` and add the lib path again, and `ldconfig` to enable it. However the error doesn't change

![image](https://user-images.githubusercontent.com/38650392/148688298-01c7f28d-2310-42b4-83fe-b12ea25f164b.png)

```bash
# some env
llvm-config --version
11.1.0
````

I wonder if the `neum` tasks support Ubuntu16/18? please give us the minimum version requirements, and we could consider use vm or docker to build a ubutnu21 for studying.

**Comment by sashimi-yzh** [comment]
We did not test the project over every distributions to find the minimum version requirements. It is recommended to use the version mentioned  in the gitbook.

**Comment by darkduckgo** [comment]
> We did not test the project over every distributions to find the minimum version requirements. It is recommended to use the version mentioned in the gitbook.

thanks a lot, and I solve the problem by using `apt` way instead of binary pkg, others can refer like:

```bash
`wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh`
 # input the llvm version u need for the bash input
`sudo ./llvm.sh 11` 
# in this way, the apt will download llvm-config-11 instead llvm-config (which in binary package)
```

**Comment by darkduckgo** [comment]
@sashimi-yzh  sorry to interrupt, after I buy a vps from cloud server, install the ubuntu21.04 server & it works well now.

however, I found some tasks seems rely on Ubuntu GUI? (like sound, and vedio/media)  [e.g. fceux-am can't run well?]

![image](https://user-images.githubusercontent.com/38650392/148884004-4e2b333d-3abb-4c19-8be3-1d4d9a5a0104.png)


but I found when our courses highlight we don't need the GUI, it makes me confuse..

![image](https://user-images.githubusercontent.com/38650392/148883810-091f8273-6b0d-48b9-b081-0b9d25a5f98d.png)


but I found the warning here, so stop the task and wonder if we need GUI (like ubuntu-desktop version), or I misunderstand the instruction?
![image](https://user-images.githubusercontent.com/38650392/148884091-3935afc1-b574-4856-8138-687c0fefe936.png)

**Comment by sashimi-yzh** [comment]
Oh, sorry for the confusion. The fact is that

**Comment by sashimi-yzh** [comment]
Oh, sorry for confusion.

The fact is that
```
1. It is unnecessary to use GUI for coding. But you can run with solutions like X11 to support graphic display.
2. We recommend to use the desktop version.
```

I am going to remove the confusing statement. Thank you.

**Comment by darkduckgo** [comment]
> Oh, sorry for confusion.
> 
> The fact is that
> 
> ```
> 1. It is unnecessary to use GUI for coding. But you can run with solutions like X11 to support graphic display.
> 2. We recommend to use the desktop version.
> ```
> 
> I am going to remove the confusing statement. Thank you.

Thanks, another question is: Can I continue with the non-GUI environment? If it doesn't affect the **core learning** & coding, I can try to continue study

**Comment by sashimi-yzh** [comment]
It requires graphic display at the middile of the assignments. Feel free to choose whether to continue or not.

**Comment by funny1dog** [comment]
> You should mention that: replace all llvm-config with llvm-config-11, lol.

**Comment by chuanchuan-Dong** [comment]
For llvm-14, the file is in"llvm/MC/TargetRegistry.h". I have solved this issue by modifing the #include " " in disasm.cc

**Comment by zwong91** [comment]
#include "llvm/MC/TargetRegistry.h"
