### ISSUE TITLE
It may not work well in WSL2

### ISSUE THREAD

**Issue by Jebearssica** [NJU-ProjectN/nemu#17]
I've tried to follow the procedure in tutorial, and an error occur when I try to compile it.

```sh
+ CXX src/utils/disasm.cc
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
+ LD $NEMU_HOME$/build/riscv32-nemu-interpreter
```

Native Ubuntu is supported systemd, but not in WSL. So I try to replace the "systemd command" with "sysvinit command", but find no way to start. So is there any suggerstion for me to start?

**Comment by Jebearssica** [comment]
Sorry for bothering, <https://github.com/MicrosoftDocs/WSL/issues/457> it has been refered that some releases are not supported for systemctl

**Comment by AlanruoyuLiu** [comment]
I had the same problem when I tried to compile it. 
So what is your final solution to this problem?

Looking forward your reply :)

> Sorry for bothering, [MicrosoftDocs/WSL#457](https://github.com/MicrosoftDocs/WSL/issues/457) it has been refered that some releases are not supported for systemctl

**Comment by Jebearssica** [comment]
> I had the same problem when I tried to compile it. So what is your final solution to this problem?
> 
> Looking forward your reply :)
> 
> > Sorry for bothering, [MicrosoftDocs/WSL#457](https://github.com/MicrosoftDocs/WSL/issues/457) it has been refered that some releases are not supported for systemctl

An easier way is installing a physical linux plantform which has been mentioned in experiment tutorial or trying to use virtual machine such as VMware.

A more complicated solution( maybe reckless? ) is replacing all the `systemctl` with suitable function ( There has been a mapping table shown in Microsoft Comunity Docs, but I can not remember the exactly url ). However, such solution seems to be unachievable, due to the complexity of this project.

**Comment by Yeijon** [comment]
I also encountered this problem.  Some calls to Linux native functions in the file will cause problems. I encountered failures when compiling the file using Windows subsystem WSL (it happened many times). For example, WSL does not seem to support `memfd_create().`
