### ISSUE TITLE
rl_gets() returns NULL on Ctrl-D causing Segmentation Fault

### ISSUE THREAD

**Issue by jiangyy** [NJU-ProjectN/nemu#2]
Attached is the suggested patch.

[fix-ctrl-d-crash-bug.txt](https://github.com/NJU-ProjectN/nemu/files/2427541/fix-ctrl-d-crash-bug.txt)

**Comment by sashimi-yzh** [comment]
Fixed in commit 5c154c8bbf0105eba4eba8039010ff4f760b73bd.
