### ISSUE TITLE
This repo has been moved to xiangshan?

### ISSUE THREAD

**Issue by Alafun** [NJU-ProjectN/nemu#20]
What's the relation between [OpenXiangShan/NEMU](https://github.com/OpenXiangShan/NEMU) and [NJU-ProjectN/nemu](https://github.com/NJU-ProjectN/nemu)?

**Comment by sashimi-yzh** [comment]
NEMU is originally an educational project in Nanjing University. see the [lecture note](https://nju-projectn.github.io/ics-pa-gitbook/ics2022/) for more information.

The XiangShan team uses NEMU as a functional model for testing. They enhance NEMU with a lot of features, which are not needed for educational propose.
