### ISSUE TITLE
无法在riscv32－pc–linux–gnu的配置下完成编译

### ISSUE THREAD

**Issue by piggy-w** [NJU-ProjectN/nemu#21]
您好，我在centos平台上编译nemu，发现出错的位置在init_disasm函数中，我尝试了去除MUXDEF，直接采用i686－pc–linux–gnu或者mipsel－pc–linux–gnu作为该函数的参数，发现编译成功。在init_disasm函数中，我发现它调用四个llvm的初始化函数，它们引入了一些后缀名为def的文件，我打开这些文件发现没有riscv，从而我尝试在.def文件中加入RISCV，但并没有解决该问题。我怀疑问题出在llvm上（12.0版），但是找不到解决方法，期待您的回复。

根据您的讲义，我重新安装了llvm，版本为11.0，目前已经能够成功编译NEMU。

**Comment by sashimi-yzh** [comment]
请你提供一下·llvm-config --versoin·的输出

**Comment by piggy-w** [comment]
根据您的讲义，我重新安装了llvm，版本为11.0，目前已经能够成功编译NEMU，谢谢！
