### ISSUE TITLE
Runing difftest may cause crash

### ISSUE THREAD

**Issue by marryjianjian** [NJU-ProjectN/nemu#24]
I had a crash when I was doing PA2-2-Differential Testing. I collapsed in getopt_long. 
The following is a screenshot of the crash.
![图片](https://user-images.githubusercontent.com/20366611/161430440-4711daad-d703-491f-a7e4-faec8bbd194f.png)

After a few traceing and debuging with nemu and glibc, I think maybe the flag `RTLD_DEEPBIND` cause this crash (Of course I am not seting CC_ASAN in Kconfig). When I just open the dynamic library with flag `RTLD_LAZY `, the program won't crash.

https://github.com/NJU-ProjectN/nemu/blob/49366fa402efdbeee305785e15ff21b8e0a660f6/src/cpu/difftest/dut.c#L51

I am not sure about the specific reason, but I hope this information is helpful.

**Comment by sashimi-yzh** [comment]
You are right. Removing `RTLD_DEEPBIND` will help. We also have a patch to fix this issue. See [here](https://github.com/NJU-ProjectN/nemu/commit/8521f46acae2ada40ad067a4c0513f504cdd42d7) for more information.

**Comment by marryjianjian** [comment]
Thanks! It solves my problem!
