### ISSUE TITLE
issue about building nemu in WSL of ubuntu20.04 instance

### ISSUE THREAD

**Issue by Le0shy** [NJU-ProjectN/nemu#32]
try to setup NEMU in WSL of ubuntu20.04 instance
>  ~/ics2021/nemu$ make

prompts for building information are below
![J_MW_}~GS(FVPQT7K4 HWTQ](https://user-images.githubusercontent.com/93461193/166664754-5c14997b-a6f4-467c-bb6f-133d98ca4a85.png)
> System has not been booted with systemd as init system (PID 1).
   Can't operate.Failed to create bus connection: Host is down

which is a quite typical problem that **WSL doesn't use Systemd and systemctl command instead of Sysvinit command**. Is there any way to fix this issue without installing other third-party tools for systemctl in WSL?

**Comment by sashimi-yzh** [comment]
If you are not takign the ICS course in NJU, you can disable the git tracing in Makefile. Please refer to the lecture note for details.

**Comment by sashimi-yzh** [comment]
Also, this issue is related to WSL. So maybe it is better to ask in the WSL community.
