### ISSUE TITLE
.config does not exists 

### ISSUE THREAD

**Issue by izlyforever** [NJU-ProjectN/nemu#34]
$ make menuconfig      

ics2021/nemu/scripts/config.mk:5: Warning: .config does not exists!
ics2021/nemu/scripts/config.mk:6: To build the project, first run 'make menuconfig'.
+ YACC build/parser.tab.h
make[1]: bison: No such file or directory
make[1]: *** [Makefile:27: build/parser.tab.h] Error 127
make: *** [ics2021/nemu/scripts/config.mk:24: ics2021/nemu/tools/kconfig/build/mconf] Error 2

=========================
Dir: ~/ics2021/nemu
Distro: Ubuntu 22.04 LTS 
Kernel: Linux 5.15.0-27-generic
GCC: 11.2.0
LLVM: 14.0.0

**Comment by izlyforever** [comment]
已解决
$ sudo apt install bison
$ sudo apt install flex
即可，一开始以为是缺少 .config 问题～

**Comment by bensstark** [comment]
OH,Thank you sir!

**Comment by bensstark** [comment]
Just about to STFW and prepare to waste so much time on it ,oh,thank you sir!

**Comment by cuzperf** [comment]
@bensstark You may consider it as another way of training

**Comment by Ferry-200** [comment]
同样被 .config does not exists! 的 warn 骗了。其实只要肯 stfw "bison: No such file or directory" 就可以找到解决方案。
