### ISSUE TITLE
请问前辈2021版的PA是没有x86和mips32指令集架构了吗？

### ISSUE THREAD

**Issue by SnakeHit** [NJU-ProjectN/nemu#36]
如题

**Comment by sashimi-yzh** [comment]
對, 沒有了, 當時對代碼做了重構, 沒來得及加回來就開學了.

後面有時間的話會把它們加回來.

**Comment by SnakeHit** [comment]
> 對, 沒有了, 當時對代碼做了重構, 沒來得及加回來就開學了.
> 
> 後面有時間的話會把它們加回來.

那前辈目前建议是做2020版的PA还是2021版PA呢？
本人有少许x86指令集的知识，没了解过riscv32。

**Comment by sashimi-yzh** [comment]
這個看你的興趣吧, 不是修讀課程的話, 都可以.

**Comment by SnakeHit** [comment]
好的，非常感谢
