### ISSUE TITLE
考虑添加license声明

### ISSUE THREAD

**Issue by alexfanqi** [NJU-ProjectN/nemu#37]
似乎这个项目没有license，我在源码中也没找到相关声明。

觉得做为开源项目很有必要添加一个license。主要下游打包和有些用户可能需要明确的license，比如gentoo每个包都要license。其次是永远无法预测谁会用何种方式滥用这个项目，之前有过些经典案例。

**Comment by sashimi-yzh** [comment]
你好, 我们这两天会进行license的添加, 感谢指出.

**Comment by sashimi-yzh** [comment]
已在[29fd6af](https://github.com/NJU-ProjectN/nemu/commit/29fd6af58df98ff102f09ff68a3e0972b13c1e99)中添加.
