### ISSUE TITLE
Mac OS 编译时缺少相关库

### ISSUE THREAD

**Issue by JosephQiu21** [NJU-ProjectN/nemu#39]
用 `make menuconfig` 生成配置文件时出现：

``` bash
ld: library not found for -ltinfo
```

请问缺少的库如何安装？是否必须在 Linux 下编译？

**Comment by JosephQiu21** [comment]
将 tools/kconfig/Makefile 中依赖项 -ltinfo 删除，暂时没有问题。

**Comment by sashimi-yzh** [comment]
感谢尝试, 已在commit ea9758d 中删除
