### ISSUE TITLE
指令实现部分宏层数太多了

### ISSUE THREAD

**Issue by tjy-zhu** [NJU-ProjectN/nemu#40]
宏一层层套 看起来非常费劲 严重牺牲了可读性 本来指令很简单的 我想学生在做作业的时候一定也花了大量时间去理清楚这些宏

**Comment by sashimi-yzh** [comment]
这是可读性和可维护性的折中, 如果全部展开来写, 看着很简单, 但代码很难维护, 到处都是重复的代码, 一处错处处错. 花一些时间读懂这些宏, 可以节省将来调试的时间.
