### ISSUE TITLE
在PA2.3，安装Spike之后再次运行nemu遇到了问题（disasm.cc链接错误）

### ISSUE THREAD

**Issue by paperplane03** [NJU-ProjectN/nemu#42]
试着根据该区域的讲义中进行调试，但无论如何均没有效果。
STFW，但没有查询到有关信息。
第一次编译出现了绿框的“可以忽略如下结果”的提示，也可以进入nemu，但再次make run便出错。
已安装device-tree-compiler，反复查看了讲义。
重装了一次llvm，确定了版本是llvm11；也查看了PA0的末尾的设置和NEMU的issue以修改，均无用。
报错信息如图：
![捕获](https://user-images.githubusercontent.com/83905880/180741039-410d0d99-754d-41b6-9f97-da96c14ec965.PNG)
![捕获2](https://user-images.githubusercontent.com/83905880/180741049-983ee381-099e-4dc5-9deb-d3db308a1871.PNG)
![捕获3](https://user-images.githubusercontent.com/83905880/180741052-b8111798-630c-4c61-81bc-c3a1da6c4258.PNG)

**Comment by sashimi-yzh** [comment]
请提供详细的操作说明, 帮助我们复现这个问题. 复现后, 我们才能更好地帮助你解决这个问题.

**Comment by paperplane03** [comment]
我测试了备份节点，发现仍然无法链接。于是我认为这可能是操作系统的某个部分出现了问题。我打算先重装一下虚拟机（目前是Ubuntu21.04，好像也已经不受支持。），判断一下这是不是因为文件夹缺损文件或者系统的问题。
谢谢老师，如果是代码的问题，我将进行diff测试来判断是哪里出了问题，并试图复现。当然，我还是希望重装系统可以解决这个问题XD

**Comment by paperplane03** [comment]
重装系统后此问题仍然无法解决，现在可知的是，将该文件make run后便能得到同样的问题。
我并不知道“贴上文件”以“进行复现”是否是符合提问/请求帮助规范，如果我这样做不妥当的话也请和我说一声，我就close issue了。
[nemu.zip](https://github.com/NJU-ProjectN/nemu/files/9248257/nemu.zip)

**Comment by paperplane03** [comment]
> 请提供详细的操作说明, 帮助我们复现这个问题. 复现后, 我们才能更好地帮助你解决这个问题.

此外可以确定的是，我用git log向前了数十个节点，make run后均有此问题。

**Comment by paperplane03** [comment]
我基本满足PA2结尾所说，对nemu的构造已经基本清楚了。但LLVM相关的代码我仍然无法理解，故无法debug......

**Comment by sashimi-yzh** [comment]
你的scripts/build.mk:41有一个`-e`参数, 去掉就解决问题了

**Comment by paperplane03** [comment]
谢谢老师，我明白了为什么会有这样的错误了。
因为-E是我之前为了展开宏做的尝试（输成-e也许是我的问题），后来用-save-temps阅读.i代码，我才理解E-helper函数、IDTAB等的构造和实现，也从中收获了许多。
记得我之前的确改过这一块（build.mk）的代码实现，但我也从来没把问题往这方面考虑，而是选择了将bug的输出信息进行STFW，最终也自然一无所获。
我是南京大学21级人工智能专业的学生，在入学前我就已经听说大名鼎鼎的PA。我对于这样“闯关”形式的讲义很感兴趣，因此我在一上就开始进行尝试。
PA0的感想让我记忆深刻，我深刻的领悟了STFW和PA0中提到的其它思想，PA0讲义中提到的“程序设计基础”课程的不足我也有意识的进行了学习。寒假中我完成了PA1，我记得自己花了三天时间一口气做完，从中收获和成就感颇多。但我也如讲义中所说“看着许多代码让我心灵感到了恐惧”。
下学期中，我学习了CMU的CSAPP课程，其中的很多Lab也让我印象深刻，和专业开设的DLCO课程一起，让我学会了x86和riscv32的知识，让我有了信心继续完成，同时jyy老师2020年的ICS实验课视频也让我有了更多的认识。
我发现无论是nemu还是makefile都没那么难理解，在preprocessor处理后，原本难以理解macro我也可以选择“跳过”，直接看预处理后的代码。
我意识到RTL对我实现riscv32指令的帮助真的很大，pseudo.h中的补全让我想到了CSAPP的datalab，我当时甚至觉得，设置了那么全的RTL是不是有点把这块的难度降得有点低（划掉）。
在遇到这个问题之前，我遇到的问题是：我可以过去所有的非字符串样例，但过不去string和hello-str（HIT BAD TRAP）。我debug了很久，过去了string测试点（问题出在decode.c），但hello-str仍然过不去。
我调试很久无果后继续翻，看到了difftest，这时我才意识到原来还有这样的美事！然后我试图安装Spike，这个问题就产生了。关于这点，我想对讲义提出一个小建议：“如果在某个地方卡住了，可能不仅仅需要向前重新阅读讲义，往后阅读一段讲义也有可能找到解决问题的更好方法。”（比如基础设施（2）在AM这一章之后，但我觉得基础设施（2）的一个目的恰好是解决AM这一节的问题，这个顺序或许有点不合适？）
最后，还是感谢老师的解答！
