### ISSUE TITLE
NEMU_HOME= is not a NEMU repo.  Stop.

### ISSUE THREAD

**Issue by yinxx** [NJU-ProjectN/nemu#47]
NEMU_HOME= is not a NEMU repo.  Stop.

**Comment by sashimi-yzh** [comment]
我这是好的.

**Comment by sashimi-yzh** [comment]
本身就支持.

**Comment by mcx222** [comment]
兄弟你这个NEMU_HOME= is not a NEMU repo. Stop.是怎么解决的，我echo输出的路径是对的，但他就是报这个错误

**Comment by yinxx** [comment]
我最近在忙别的事情，这个bug我还没有找到怎么解决？
b4nm121我的wx










在 2023-05-27 21:12:03，"mcx222" ***@***.***> 写道：

兄弟你这个NEMU_HOME= is not a NEMU repo. Stop.是怎么解决的，我echo输出的路径是对的，但他就是报这个错误

**Comment by hyn1426536274** [comment]
我也遇到了，知道你们是不是这个问题：
提示Makefile 18行出错，打开Makefile一看是由于$NEMU_HOME / src / nemu-main.c 为空。
但实际上有这个文件，猜测是原因是 $NEMU_HOME 为空，
echo $NEMU_HOME 确实为空
所以source ~/.bashrc
然后再次echo $NEMU_HOME 打印了正确的路径
现在执行make menuconfig 就成功了
