### ISSUE TITLE
makefile中-werror会导致/nemu/tools/qemu-diff编译不通过

### ISSUE THREAD

**Issue by QAQ-555** [NJU-ProjectN/nemu#48]
![屏幕截图 2022-09-26 133740](https://user-images.githubusercontent.com/91819649/192201300-f486526a-6318-4170-9f37-dff65bf6920a.png)
在ubuntu环境下，ics2020/nemu中，运行`make ISA=mips32 run`
会出现以上报错导致无法编译，删除Makeflie中`-Werror`后可以通过，但不知道后续有无影响

**Comment by sashimi-yzh** [comment]
试试 #12 是否能修复这个问题?

**Comment by QAQ-555** [comment]
> 

能修复该问题
