### ISSUE TITLE
关于声卡的适配

### ISSUE THREAD

**Issue by paperplane03** [NJU-ProjectN/nemu#49]
老师您好，我在PA2中实现了声卡并通过了Audio_test（有声音）。
但带音效的红白机版本我无法正常运行，会卡在Initialize audio处不再继续，开始会有一小段电流声。经检测，将声音改为HQ_SOUND_NONE可以正常使用。
因为这是选做部分，所以我问了助教和老师也没有得到答复。请问这个版本的PA是否可以使用声卡？

**Comment by sashimi-yzh** [comment]
这个版本的PA可以使用声卡, 前段时间有不少同学都可以成功运行

**Comment by paperplane03** [comment]
谢谢老师，我会继续自己做下去。
