### ISSUE TITLE
make_token()中的no match报错输出对长到折行的表达式不友好

### ISSUE THREAD

**Issue by azure-crab** [NJU-ProjectN/nemu#5]
nemu/src/monitor/debug/expr.c: 91行在无法匹配时输出错误位置的代码：
printf("no match at position %d\n%s\n%*.s^\n", position, e, position, "");
没有考虑e过长导致折行的情况，这样可能导致'^'指向错误的位置，希望能在guidebook中增加相关提示。
例：
![tim 20181207181906](https://user-images.githubusercontent.com/16447524/49642524-43ff5480-fa4e-11e8-91d4-6aa62ca7a00b.png)
这个例子里我检测十六进制表达的正则实现有误，但是由于表达式过长造成折行，导致‘^‘指向了折行后的'-'。

**Comment by sashimi-yzh** [comment]
gcc的輸出也是這樣的, 當一行代碼過長的時候, 就會出現這個現象.

在這種情況下, 建議通過position的數字來定位.

**Comment by azure-crab** [comment]
是的，不过是不是可以考虑在guide book里面提醒一下可能会出现这种情况？
避免有人跟我一样犯傻还没意识到发生了什么……

**Comment by azure-crab** [comment]
是的，不过是不是可以考虑在guidebook里面提醒一下呢？
避免有人跟我一样犯傻还没意识到发生了什么。

**Comment by sashimi-yzh** [comment]
已經加入提醒, 最近更新內容較多, 過段時間一起push, 感謝你的建議!

**Comment by Michael1015198808** [comment]
If it's not neccessary to print all the code, you can do it in this way.
`printf("An error occurs somewherE\f\b^\n");`
