### ISSUE TITLE
请问哪里可以找到 x86 的 isa？

### ISSUE THREAD

**Issue by Yjsmall** [NJU-ProjectN/nemu#52]
- clone PA2022 实验册，在 `nemu/src/isa` 这个文件夹只有 `riscv32` 以及 `riscv64` 这两个 ISA 指令集架构。
- `make menuconfig` 选择 `x86` 的 ISA 之后，再进行 `make` 编译，发现它无法找到 `x86` 的 `isa-def.h` 文件。

而这里的仓库也没有 `x86` 的 ISA，只有 `riscv32`，`riscv64`， `mips32`以及`longarch32` 的 ISA。
我在 GitHub 找了好久也没有发现，所以请问哪里可以找见？

**Comment by sashimi-yzh** [comment]
2021年重构代码之后一直没时间维护x86的代码, 需要的话可以参考2020年的代码.

**Comment by sashimi-yzh** [comment]
已在`ics2024`分支中重新发布x86的代码
