### ISSUE TITLE
启用difftest后出现段错误

### ISSUE THREAD

**Issue by zhaoyongchao2019** [NJU-ProjectN/nemu#55]
我使用GDB调试后定位出错的位置如下图标记
![image](https://user-images.githubusercontent.com/50958273/221543531-a83f677a-3bf6-465c-8283-02ef98aff949.png)
已经尝试上网寻找但无果，希望老师看到能解答一下

**Comment by zhaoyongchao2019** [comment]
![image](https://user-images.githubusercontent.com/50958273/221548649-ffbd1395-ffae-4154-b28f-b5c8c8c9f524.png)
出错的提示信息

**Comment by sashimi-yzh** [comment]
先试试ics2022

**Comment by zhaoyongchao2019** [comment]
老师，我不是南京大学的学生，可能ics2022现在还有一些权限的限制，我试不了ics2021

**Comment by zhaoyongchao2019** [comment]
老师，你是想让我尝试使用ics2022 spike-diff去替换2021对应的文件是吗？但由于我不是南京大学的学生，我在替换了ics2022 spike-diff后make会报错，好像是因为我没有这个权限。

**Comment by sashimi-yzh** [comment]
不是, 是直接clone ics2022来做, 可以把大部分的現有代碼拷過去

**Comment by zhaoyongchao2019** [comment]
但是现在ics2022项目好像对非南京大学的学生不公开？我clone不了2022的版本，它会提示没有权限

**Comment by sashimi-yzh** [comment]
一直都是公开的, 沒有关闭过

**Comment by zhaoyongchao2019** [comment]
好的，我后面尝试ics2022看看，感谢老师的解答。我很感激能有这么一个项目能让我们去学习计算机系统，感谢你们的努力。

**Comment by sashimi-yzh** [comment]
感謝你的認可, 祝你學有所成 :)
