### ISSUE TITLE
编译【spike-diff】时终端报【error: 'optional' in namespace 'std' does not name a template type】错误

### ISSUE THREAD

**Issue by myyerrol** [NJU-ProjectN/nemu#62]
**开发环境**
系统版本：WSL2 Ubuntu 20.04.5 LTS
GCC版本：9.4.0 (Ubuntu 9.4.0-1ubuntu~20.04.1)
指令架构：riscv64

**问题描述**
在开启`CONFIG_DIFFTEST`宏之后，在`nemu`目录下执行`make run`命令，终端会报很多类似下图中的错误。
![image](https://user-images.githubusercontent.com/4677346/231384786-b86b5b83-51f0-483c-978e-b162bf2fbb53.png)

**原因分析**
结合报错信息上网查找相关资料，得知`optional`是C++17标准中引入的新功能，而9.4.0版本的GCC默认使用的是C++11标准，所以需要在编译时通过参数指定C++标准版本。于是接下来我排查了动态生成的`spike-diff/repo/build/Makefile`文件，发现C++编译选项中已经添加了`-std=c++17`参数，即已经开启了对C++17标准的支持。但是为什么还会出现这种问题？`optional`是在GCC 7.2中首次从实验标准转为正式标准，GCC 9中肯定也存在。

后来终于发现在`nemu/tools/spike-diff/Makefile`中添加`-std=c++17`能编译成功，可是编译出错的位置是在`spike`仓库内部，并不在`spike-diff`中，说明在编译生成spike的静态链接库时编译依赖会向上传递？总之，该问题应该与GCC版本有关，某些版本的编译器需要手动添加参数。

**问题发现者**
@Jasonyanyusong 
@myyerrol

**解决方案**
如下图所示，在`nemu/tools/spike-diff/Makefile`文件中的编译选项中添加`-std=c++17`即可。
![image](https://user-images.githubusercontent.com/4677346/231384687-95a24bee-ec47-4ca6-855f-e1569dae9f97.png)

**Comment by sashimi-yzh** [comment]
fix in #63
