### ISSUE TITLE
question about the difftest code

### ISSUE THREAD

**Issue by fuxinyuan1998** [NJU-ProjectN/nemu#66]
I have a question about the difftest
in the file src/isa/riscv64/local-include/reg.h
`static inline const char* reg_name(int idx, int width) {
  extern const char* regs[];
  return regs[check_reg_idx(idx)];
}
`
why there is a parameter 'width' not used

**Comment by fuxinyuan1998** [comment]
and I get an error which is `make[2]: Circular libriscv.so <- libriscv.so dependency dropped.` when I turn on the difftest option.
when I excute 'make run', the program has been excuted successfully. but when I debug it, the program will trigger the assertion of 'dlopen', and I have no idea about this. Could you give me some tips or hints?
![image](https://github.com/NJU-ProjectN/nemu/assets/53423018/cbb96482-eea6-4940-99f9-ce03d93f3f6a)

**Comment by sashimi-yzh** [comment]
Does `ref_so_file` exist? If not, please try to check why. The `Makefile`s should contain rules to build `ref_so_file`.

For the `width` parameter, it is used in x86. So you can ignore it in riscv64.

**Comment by fuxinyuan1998** [comment]
I believe I am sure the file exits and the path is right and I write a program to test it. the test open it  successfully but it cant work in nemu. here is the program.

`#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <stdbool.h>
#include <assert.h>

#define LIB_CALCULATE_PATH "./riscv64-spike-so"

typedef int (*CAC_FUNC)(int, int);

int main()
{
    void *handle;
    char *error;
    CAC_FUNC cac_func = NULL;
    handle = dlopen(LIB_CALCULATE_PATH, RTLD_LAZY);
    if(!handle){
        fprintf(stderr, "%s\n", dlerror());
        exit(EXIT_FAILURE);
    }else{
        printf("successfull!\n");
    }
    assert(handle);
}`

**Comment by sashimi-yzh** [comment]
What does `dlerror()` report in NEMU?

**Comment by fuxinyuan1998** [comment]
when I debug it with gdb, the handle gets 0x0 and `dlerror` report "no such file or directory"
![image](https://github.com/NJU-ProjectN/nemu/assets/53423018/7bb0a7fd-a940-4691-b890-9e8a06de3909)
but when I excute `make run`, there is nothing wrong happend but the "difftest" function has not been implemented
![image](https://github.com/NJU-ProjectN/nemu/assets/53423018/38447260-5322-4a5f-a5bd-ff40f6d88e4f)

**Comment by sashimi-yzh** [comment]
According to the message reported by `dlerror()`, it seems that there is a trailing space in the `ref_so_file` string. You may remove it and retry.

**Comment by fuxinyuan1998** [comment]
Thank you pretty much and I solve it. 
Thank you for your reply again Dr.
