### ISSUE TITLE
A typo(maybe) in macro.h

### ISSUE THREAD

**Issue by western-mahua** [NJU-ProjectN/nemu#71]
https://github.com/NJU-ProjectN/nemu/blob/b7b09f8918931e9c725ed3366b7a15588529d6a2/include/macro.h#L93
Should it be `__attribute__` instead?

**Comment by sashimi-yzh** [comment]
They are then same. See https://stackoverflow.com/questions/52514963/the-difference-between-attribute-unused-and-attributeunused-in-gcc for more details.
