### ISSUE TITLE
Suggestion: PA2的顺序修改

### ISSUE THREAD

**Issue by dream-tentacle** [NJU-ProjectN/nemu#79]
在PA2第一部分"RTFSC(2)"的末尾，要求学生通过`string`和`hello-str`以外的所有测试样例，但difftest到PA2最后一部分才提出，这让习惯一步一步做的学生可能花费大量低效的时间来调试实现错误的指令。建议将difftest移到第一部分最后面。

**Comment by sashimi-yzh** [comment]
这是我们考虑之后的决定, 需要让学生先稍微吃点苦头, 才能明白自己实现工具的重要性, 而不是把difftest当做一个天上掉下来的馅饼.
