### ISSUE TITLE
Maybe need libboost as dependencies

### ISSUE THREAD

**Issue by q2333gh** [NJU-ProjectN/nemu#86]

**Comment by q2333gh** [comment]
I have check nju-ics-pa gitbook. dont tell user to install this :

```BASH
...

checking whether the Boost::ASIO library is available... yes
configure: error: Could not find a version of the Boost::Asio library!
make[1]: *** [Makefile:25: repo/build/Makefile] Error 1
make: *** [/home/btwl/code/ICS_OS_study/nju_ics2023/nemu/tools/difftest.mk:24: /home/btwl/code/ICS_OS_study/nju_ics2023/nemu/tools/spike-diff/build/riscv64-spike-so] Error 2
...
```
 `sudo apt-get install -y libboost-all-dev`

**Comment by sashimi-yzh** [comment]
This is the dependency of spike. Refer to the README of spike.

The gitbook is not responsible for telling you every detail. Learn to find the solution by yourself.

**Comment by q2333gh** [comment]
Thank you very much for reply . I got it ! So happy to have alot of stuff can learn
