### ISSUE TITLE
cpu_exec里状态转换存在问题

### ISSUE THREAD

**Issue by czlx-github** [NJU-ProjectN/nemu#87]
复现：在NEMU开启device时，在am-tests目录下运行video测试，然后点击关闭按钮。NEMU会回到等待输入的状态，再次运行`c`命令后程序会继续运行。

解释：
当NEMU状态为`NEMU_QUIT`（在`device_update()`里检测到关闭窗口时会设置为这个状态），但`cpu_exec()`里刚开始的状态判断没有考虑这个情况：
```
switch (nemu_state.state) {
    case NEMU_END: case NEMU_ABORT:
      printf("Program execution has ended. To restart the program, exit NEMU and run again.\n");
      return;
    default: nemu_state.state = NEMU_RUNNING;
  }
```

执行指令返回后的状态判断中，`case NEMU_QUIT: statistic();`没有退出程序，故再次运行`c`命令会导致上面的状态判断里设置NEMU的状态为`NEMU_RUNNING`，从而继续执行指令。

**Comment by sashimi-yzh** [comment]
点击窗口的关闭按钮应该会直接退出NEMU, 不会返回到等待输入的状态.

**Comment by czlx-github** [comment]
是的

**Comment by sashimi-yzh** [comment]
你可以提一个PR, 以记录你的贡献.

**Comment by czlx-github** [comment]
抱歉，个人觉得PA作为教学系统，由我修改不太合适。还是麻烦老师修复了。

**Comment by sashimi-yzh** [comment]
没关系的, 之前已经有很多热心的爱好者提了很多PR, 你可以看看已合并PR的列表.

**Comment by czlx-github** [comment]
好的，之后我提个PR修复这个问题，谢谢老师。
